/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexionntb;

import static conexionntb.ConexionNTB.con;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class PanelRelacional extends javax.swing.JDialog {

    static ArrayList<ArrayList<String>> datos;
    
    public PanelRelacional(javax.swing.JDialog parent, boolean modal,ArrayList<ArrayList<String>> datos) {
        super(parent, modal);
        this.datos=datos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(10, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("IdProv");
        jPanel1.add(jLabel1);

        jLabel2.setText("IdProd");
        jPanel1.add(jLabel2);

        jLabel3.setText("Nombre producto");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText(" ");
        jPanel2.add(jLabel4);

        jLabel5.setText(" ");
        jPanel2.add(jLabel5);

        jLabel6.setText("  ");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setText(" ");
        jPanel3.add(jLabel7);

        jLabel8.setText(" ");
        jPanel3.add(jLabel8);

        jLabel9.setText("  ");
        jPanel3.add(jLabel9);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel10.setText(" ");
        jPanel4.add(jLabel10);

        jLabel11.setText(" ");
        jPanel4.add(jLabel11);

        jLabel12.setText("  ");
        jPanel4.add(jLabel12);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel13.setText(" ");
        jPanel5.add(jLabel13);

        jLabel14.setText(" ");
        jPanel5.add(jLabel14);

        jLabel15.setText("  ");
        jPanel5.add(jLabel15);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel16.setText(" ");
        jPanel6.add(jLabel16);

        jLabel17.setText(" ");
        jPanel6.add(jLabel17);

        jLabel18.setText("  ");
        jPanel6.add(jLabel18);

        getContentPane().add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel19.setText(" ");
        jPanel7.add(jLabel19);

        jLabel20.setText(" ");
        jPanel7.add(jLabel20);

        jLabel21.setText("  ");
        jPanel7.add(jLabel21);

        getContentPane().add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel22.setText(" ");
        jPanel8.add(jLabel22);

        jLabel23.setText(" ");
        jPanel8.add(jLabel23);

        jLabel24.setText("  ");
        jPanel8.add(jLabel24);

        getContentPane().add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel25.setText(" ");
        jPanel9.add(jLabel25);

        jLabel26.setText(" ");
        jPanel9.add(jLabel26);

        jLabel27.setText("  ");
        jPanel9.add(jLabel27);

        getContentPane().add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel28.setText(" ");
        jPanel10.add(jLabel28);

        jLabel29.setText(" ");
        jPanel10.add(jLabel29);

        jLabel30.setText("  ");
        jPanel10.add(jLabel30);

        getContentPane().add(jPanel10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        rellenar();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
   /* ArrayList<ArrayList<String>> mostrardatos2(String idProdString){
        
        String sql = "SELECT * FROM proveedores WHERE Idprod = "+idProdString;
        Statement st;
        ArrayList<ArrayList<String>> datos2 = new ArrayList();
        
       for (ArrayList<String> dato : datos2) {
           datos2.add(new ArrayList());
       }
       try {
           st = con.createStatement();
           ResultSet result = st.executeQuery(sql);
           int i=0;
           while (result.next()){
               datos2.add(new ArrayList());
               datos2.get(i).add(result.getString(1));
               datos2.get(i).add(result.getString(2));
               datos2.get(i).add(result.getString(3));
               i++;  
           }
           System.out.println("testpanelrelacional2222");
       } catch (SQLException ex) {
           System.out.println("ex");
           
           
           
       }
       System.out.println(datos2.get(0).get(1));
      return datos2;
    }*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PanelRelacional dialog = new PanelRelacional(new javax.swing.JDialog(), true,datos);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
               
                
               
            
            
            
            }
           
        });
    }
    void rellenar(){
        ArrayList<ArrayList<String>> relacionados =datos;
                
                try{
                    jLabel4.setText(relacionados.get(0).get(0));
                    
                    jLabel5.setText(relacionados.get(0).get(1));
                    jLabel6.setText(relacionados.get(0).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel7.setText(relacionados.get(1).get(0));
                    jLabel8.setText(relacionados.get(1).get(1));
                    jLabel9.setText(relacionados.get(1).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel10.setText(relacionados.get(2).get(0));
                    jLabel11.setText(relacionados.get(2).get(1));
                    jLabel12.setText(relacionados.get(2).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel13.setText(relacionados.get(3).get(0));
                    jLabel14.setText(relacionados.get(3).get(1));
                    jLabel15.setText(relacionados.get(3).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel16.setText(relacionados.get(4).get(0));
                    jLabel17.setText(relacionados.get(4).get(1));
                    jLabel18.setText(relacionados.get(4).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel19.setText(relacionados.get(5).get(0));
                    jLabel20.setText(relacionados.get(5).get(1));
                    jLabel21.setText(relacionados.get(5).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel22.setText(relacionados.get(6).get(0));
                    jLabel23.setText(relacionados.get(6).get(1));
                    jLabel24.setText(relacionados.get(6).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel25.setText(relacionados.get(7).get(0));
                    jLabel26.setText(relacionados.get(7).get(1));
                    jLabel27.setText(relacionados.get(7).get(2));
                }catch (Exception ex) {
                    
                }
                
                try{
                    jLabel28.setText(relacionados.get(8).get(0));
                    jLabel29.setText(relacionados.get(8).get(1));
                    jLabel30.setText(relacionados.get(8).get(2));
                }catch (Exception ex) {
                    
                }
               
                
               
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

}
